# Generated by Django 4.2.30 on 2026-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/default.jpg', upload_to='event_images/'),
        ),
    ]
