# Generated by Django 4.2.30 on 2026-04-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='media/event_images/default.jpg', upload_to='event_images/'),
        ),
    ]
