# Generated by Django 4.2.30 on 2026-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/party.jpg', upload_to='event_images/'),
        ),
    ]
