# Generated by Django 4.2.30 on 2026-04-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dlvyzkknx/image/upload/v1776997098/calendar_cchd5s.png'),
        ),
    ]
